project:
  type: website
  output-dir: docs

website:
  title: "Sara Orofino"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - icon: github
        href: https://github.com/saraorofino
      - icon: twitter
        href: https://twitter.com/slorofino
      - icon: linkedin
        href: https://www.linkedin.com/in/sara-orofino
      - icon: envelope
        href: mailto:saraorofino@ucsb.edu

format:
  html:
    page-layout: full
    sidebar: false
    theme: theme.scss
    #css: styles.css
    mainfont: Nunito Sans
    toc: true

editor: visual

